ARG BASE=606191926999.dkr.ecr.us-east-1.amazonaws.com/bitnami-legacy-images:keycloak-26.3.2-debian-12-r2

FROM ${BASE}

COPY --chown=1001:1001 themes/spectra-login /opt/bitnami/keycloak/themes/spectra-login


